-- 코드를 입력하세요

-- 1. 생산일자가 2022년 5월인 식품 ID, 식품 이름, 총매출 조회
-- 2. 총매출을 기준으로 내림차순 정렬, 식품 ID 기준으로 정렬

SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID