-- 코드를 입력하세요

-- 1. 각 시간대 별로 입양이 몇 건이나 발생하였는지 09:00 ~ 19:59까지
-- 2. 시간대 순으로 정렬

-- SELECT HOUR(`DATETIME`) AS HOUR, COUNT(`DATETIME`) AS COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR(`DATETIME`)
-- HAVING HOUR(`DATETIME`) < 20 and HOUR(`DATETIME`) > 9
-- ORDER BY HOUR(`DATETIME`);

SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20 
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME);